theme: jekyll-theme-architect,
title: 'React Apps Collection',
description: 'Collection of apps created using react for learning perspective. Feel free to look, explore and fork the repo for learning/enhancements perspective.'